/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.pkg.github.com/APDevTeam/Movecraft")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://raw.github.com/FabioZumbi12/UltimateChat/mvn-repo/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.br.net.fabiozumbi12.ultimatechat.ultimatechat.spigot)
    compileOnly(libs.br.net.fabiozumbi12.ultimatechat.ultimatefancy)
    system(libs.com.massivecraft.massivecore)
    system(libs.com.massivecraft.factions)
}

group = "net.TylerS1066.ufc"
version = "1.0.0_beta-1"
description = "Ultimate-FactionsChat"
java.sourceCompatibility = JavaVersion.VERSION_13

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
