name: Ultimate-FactionsChat
version: ${projectVersion}
main: net.tylers1066.ufc.UltimateFactionsChat
api-version: 1.14
depend: [UltimateChat, Factions]
authors: [TylerS1066]
description: UltimateChat + MassiveCore Factions integration
website: github yo
