name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Ultimate-FactionsChat
      uses: actions/checkout@v2
      with:
        path: Ultimate-FactionsChat
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    
    # Build Ultimate-FactionsChat
    - name: Build Ultimate-FactionsChat
      run: mvn -B package -T 1C --file Ultimate-FactionsChat/pom.xml

    - name: Stage jar
      run: mkdir staging && cp Ultimate-FactionsChat/target/Ultimate-FactionsChat.jar staging
    - name: Rename jar
      run: mv staging/Ultimate-FactionsChat*.jar staging/Ultimate-FactionsChat_$GITHUB_SHA.jar
    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: Ultimate-FactionsChat_Dev-Build
        path: staging/Ultimate-FactionsChat_*.jar
